[alias]
xtask = 'run -p xtask --'
nrf52840 = 'run -p xtask --features nrf52840 -- nrf52840'
stm32f411 = 'run -p xtask --features stm32f411 -- stm32f411'
stm32f446 = 'run -p xtask --features stm32f446 -- stm32f446'
stm32f469 = 'run -p xtask --features stm32f469 -- stm32f469'
stm32h723 = 'run -p xtask --features stm32h723 -- stm32h723'
stm32f746 = 'run -p xtask --features stm32f746 -- stm32f746'
stm32f334 = 'run -p xtask --features stm32f334 -- stm32f334'
rp2040 = 'run -p xtask --features rp2040 -- rp2040'
rpi4 = 'run -p xtask -- rpi4'
